import type { Docente } from "@/types/docente";

const docentesCarreraAgronomica : Docente[] = [
  {
    nombreCompleto: "Jorge Zamir Erazo Amaya",
    nombre: "Jorge",
    apellido: "Erazo",
    cargo: "Decano de Facultad",
    grado: "M.Sc.",
    area: "Área de desempeño profesional: Producción agrícola.",
    correo: "zerazo@unag.edu.hn",
  },
  {
    nombreCompleto: "Doris Alajandrina Izaguirre Osorio",
    nombre: "Doris",
    apellido: "Izaguirre",
    cargo: "Asistente de la Decanatura, Pedagoga de la coordinación",
    grado: "Licenciada en Pedagogía y Ciencias de la Educación",
    area: "Área de desempeño profesional: Coordinación de la carrera de Ingeniería Agronómica.",
    correo: "dizaguirre@unag.edu.hn",
  },
  {
    nombreCompleto: "Alejandro José Rápalo Cruz",
    nombre: "Alejandro",
    apellido: "Rápalo",
    cargo: "Docente",
    grado: "M.Sc. en Economía y Finanzas",
    area: "Área de desempeño profesional: Secciones de propagación de plantas.",
    correo: "arapalo@unag.edu.hn",
  },
  {
    nombreCompleto: "Sonia Bertalina Escalante Rosalas",
    nombre: "Sonia",
    apellido: "Escalante",
    cargo: "Asistente de la Coordinación Académica",
    grado: "Licenciada en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Coordinación de la carrera de Ingeniería Agronómica.",
    correo: "srosalas@unag.edu.hn",
  },
  {
    nombreCompleto: "Juany Lizeth Canelas Padilla",
    nombre: "Juany",
    apellido: "Canelas",
    cargo: "Administradora de la Facultad",
    grado: "Lic. Administración de Empresas Agropecuaria",
    area: "Área de desempeño profesional: Área administrativa.",
    correo: "",
  },
  {
    nombreCompleto: "Raúl Isaías Muñoz Hernández",
    nombre: "Raúl",
    apellido: "Muñoz",
    cargo: "Docente",
    grado: "M.Sc. en Scientiae en Entomologia",
    area: "Área de desempeño profesional: Ciencia.",
    correo: "rmuñoz@unag.edu.hn",
  },
  {
    nombreCompleto: "José Andres Paz Díaz",
    nombre: "José",
    apellido: "Paz",
    cargo: "Jefe de Departamento Académico de Horticultura",
    grado: "M.Sc. en Gerencia de Proyectos de desarrollo",
    area: "Área de desempeño profesional: Sección de hortalizas.",
    correo: "jpaz@unag.edu.hn",
  },
  {
    nombreCompleto: "Héctor Leonardo Raudales Peralta",
    nombre: "Héctor",
    apellido: "Raudales",
    cargo: "Jefe de Departamento Académico de Ingeniería Agrícola, Docente",
    grado: "M.Sc. en Gestión de Proyectos de energias Renovables",
    area: "Área de desempeño profesional: Ingeniería Agrícola.",
    correo: "hraudalas@unag.edu.hn",
  },
  {
    nombreCompleto: "Gustavo Ramón López Hernández",
    nombre: "Gustavo",
    apellido: "López",
    cargo: "Jefe del Departamento de Producción Vegetal, Docente",
    grado: "M.Sc. en Fitotecnia",
    area: "Área de desempeño profesional: Sección de diseño experimental.",
    correo: "",
  },
  {
    nombreCompleto: "Adán Alvarado Ramírez",
    nombre: "Adán",
    apellido: "Alvarado",
    cargo: "Docente/Asistente de Laboratorio de Entomopatógenos",
    grado: "M.Sc. en Agricultura Sostenible Mención Sanidad Vegetal",
    area: "Área de desempeño profesional: Docente adscrito al Departamento de Horticultura.",
    correo: "aaramirez@unag.edu.hn",
  },
  {
    nombreCompleto: "Adrián Francisco Reyes Martínez",
    nombre: "Adrián",
    apellido: "Reyes",
    cargo: "Coordinador de la Carrera Segundo y Cuarto Año",
    grado: "M.Sc. Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Sección de hidráulica y riegos.",
    correo: "areyes@unag.edu.hn",
  },
  {
    nombreCompleto: "Alex Fabián López Rivera",
    nombre: "Alex",
    apellido: "López",
    cargo: "Coordinador de la Carrera Primer y Tercer Año",
    grado: "M.Sc. Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Sección de hortalizas.",
    correo: "axlopez@unag.edu.hn",
  },
  {
    nombreCompleto: "Ariel Adonis López Salgado",
    nombre: "Ariel",
    apellido: "López",
    cargo: "Docente",
    grado: "M.Sc. en Gestión de Proyectos",
    area: "Área de desempeño profesional: Topografía, construcciones rurales, hidráulica.",
    correo: "alopez@unag.edu.hn",
  },
  {
    nombreCompleto: "Carlos Humberto Amador Zelaya",
    nombre: "Carlos",
    apellido: "Amador",
    cargo: "Docente",
    grado: "Magíster en Ciencias Vegetales",
    area: "Área de desempeño profesional: Fisiología del rendimiento, granos y cerealas.",
    correo: "camador@unag.edu.hn",
  },
  {
    nombreCompleto: "Eduardo Ariel Castro Blandín",
    nombre: "Eduardo",
    apellido: "Castro",
    cargo: "Docente",
    grado: "M.Sc. en Riego y Drenaje",
    area: "Área de desempeño profesional: Ingeniería agrícola, especialista en riegos.",
    correo: "eacastro@unag.edu.hn",
  },
  {
    nombreCompleto: "Favián Antonio Salgado Archaga",
    nombre: "Favián",
    apellido: "Salgado",
    cargo: "Docente",
    grado: "M.Sc. en Ciencia en Sanidad Vegetal",
    area: "Área de desempeño profesional: Frutales y fitopatología.",
    correo: "fsalgado@unag.edu.hn",
  },
  {
    nombreCompleto: "Hilsy Lourdes Sanabria Ortega",
    nombre: "Hilsy",
    apellido: "Sanabria",
    cargo: "Coordinadora del laboratorio de Biotecnología, Docente",
    grado: "M.Sc. Science en Recursos Fitogeneticos",
    area: "Área de desempeño profesional: Genética y propagación de plantas.",
    correo: "",
  },
  {
    nombreCompleto: "Jorge Alberto Medina Peña",
    nombre: "Jorge",
    apellido: "Medina",
    cargo: "Docente",
    grado: "M.Sc. en Gestión de Proyectos",
    area: "Área de desempeño profesional: Asistente de sección de fruticultura.",
    correo: "",
  },
  {
    nombreCompleto: "Jorge Ernesto Guevara Ohara",
    nombre: "Jorge",
    apellido: "Guevara",
    cargo: "Docente",
    grado: "M.Sc. en Ciencias Agrarias",
    area: "Área de desempeño profesional: Fisiología y fitomejoramiento.",
    correo: "jguevara@unag.edu.hn",
  },
  {
    nombreCompleto: "José Antonio Ramírez Alvarado",
    nombre: "José",
    apellido: "Ramírez",
    cargo: "Docente",
    grado: "M.Sc. en Administración de Empresas",
    area: "Área de desempeño profesional: Manejo de malazas, granos y cerealas.",
    correo: "jramirez@unag.edu.hn",
  },
  {
    nombreCompleto: "José Santiago Maradiaga Rodríguez",
    nombre: "José",
    apellido: "Maradiaga",
    cargo: "Docente",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Seminario, hortalizas y horticultura.",
    correo: "smaradiaga@unag.edu.hn",
  },
  {
    nombreCompleto: "Ramon Rosalio Rosales",
    nombre: "Ramon",
    apellido: "Rosales",
    cargo: "Docente",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Investigación y extensión.",
    correo: "rrosalas@unag.edu.hn",
  },
  {
    nombreCompleto: "René Gerardo Cáceres Torres",
    nombre: "René",
    apellido: "Cáceres",
    cargo: "Docente Daia Director del Sistema de Centros Regionales",
    grado: "M.Sc. en Gerencia de Proyectos de desarrollo",
    area: "Área de desempeño profesional: Ingeniería Agrícola y área de proyectos.",
    correo: "rcaceres@unag.edu.hn",
  },
  {
    nombreCompleto: "Reynaldo Eliseo Flores Gómez",
    nombre: "Reynaldo",
    apellido: "Flores",
    cargo: "Docente",
    grado: "M.Sc. en Sanidad Vegetal",
    area: "Área de desempeño profesional: Granos y cerealas y sanidad vegetal.",
    correo: "rflores@unag.edu.hn",
  },
  {
    nombreCompleto: "Roy Donald Menjivar Barahona",
    nombre: "Roy",
    apellido: "Menjivar",
    cargo: "Docente Investigador",
    grado: "Ph. D. Ciencias Agrarias con Orientación en Manejo de Plagas",
    area: "Área de desempeño profesional: Entomología, seminario de investigación y fruticultura.",
    correo: "rmenjivar@unag.edu.hn",
  },
  {
    nombreCompleto: "Yoni Soriel Antúnez Munguía",
    nombre: "Yoni",
    apellido: "Antúnez",
    cargo: "Docente",
    grado: "M.Sc. en Ciencias en Sanidad Vegetal",
    area: "Área de desempeño profesional: Producción vegetal cultivos industriales.",
    correo: "yantunez@unag.edu.hn",
  },
  {
    nombreCompleto: "Juan Alberto Chavarria Araujo",
    nombre: "Juan",
    apellido: "Chavarria",
    cargo: "Docente",
    grado: "M. Sc. Gestión de Riesgo y Manejo de desastres",
    area: "Área de desempeño profesional: Agroclimatologia, riegos y manejo de desastres.",
    correo: "jchavarria@unag.edu.hn",
  },
  {
    nombreCompleto: "Manuel Alberto Chavarría Sierra",
    nombre: "Manuel",
    apellido: "Chavarría",
    cargo: "Docente",
    grado: "M. Sc. Gestión de energía Renovable",
    area: "Área de desempeño profesional: Tecnología apropiada e hidráulica y riegos.",
    correo: "mchavarria@unag.edu.hn",
  },
  {
    nombreCompleto: "Moises Armando Chavarría Sierra",
    nombre: "Moises",
    apellido: "Chavarría",
    cargo: "Docente",
    grado: "M. Sc. Gestión de Proyectos",
    area: "Área de desempeño profesional: Topografía y construcciones rurales.",
    correo: "mochavarria@unag.edu.hn",
  },
  {
    nombreCompleto: "Allan Javier Rivera Carbajal",
    nombre: "Allan",
    apellido: "Rivera",
    cargo: "Docente",
    grado: "M. Sc. Gestión de Proyectos",
    area: "Área de desempeño profesional: Topografía, construcciones rurales.",
    correo: "",
  },
  {
    nombreCompleto: "Jorge Alberto Calix Orellana",
    nombre: "Jorge",
    apellido: "Calix",
    cargo: "Docente",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Mecanización agrícola.",
    correo: "jcalix@unag.edu.hn",
  },
  {
    nombreCompleto: "Efraín Paz Molina",
    nombre: "Efraín",
    apellido: "Paz",
    cargo: "Docente",
    grado: "Licenciado en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Mecanización agrícola.",
    correo: "epaz@unag.edu.hn",
  },
  {
    nombreCompleto: "Carlos Joel Navarro Lobo",
    nombre: "Carlos",
    apellido: "Navarro",
    cargo: "Docente",
    grado: "M. Sc. Seguridad Alimentaria",
    area: "Área de desempeño profesional: Sección de diseño y ornato de áreas verdes.",
    correo: "cnavarro@unag.edu.hn",
  },
  {
    nombreCompleto: "Fredy Rolando Juárez",
    nombre: "Fredy",
    apellido: "Juárez",
    cargo: "Docente",
    grado: "Pasante de M.Sc. en Economia y Planificación del desarrollo",
    area: "Área de desempeño profesional: Sección de tecnología apropiada.",
    correo: "",
  },
  {
    nombreCompleto: "Mario Roberto Rivera Carbajal",
    nombre: "Mario",
    apellido: "Rivera",
    cargo: "Docente",
    grado: "M. Sc. Gestión de Proyectos",
    area: "Área de desempeño profesional: Topografía, construcciones rurales.",
    correo: "",
  },
  {
    nombreCompleto: "Porfirio Bismar Hernández",
    nombre: "Porfirio",
    apellido: "Hernández",
    cargo: "Jefe de Sección de Granos y Cerealas, Coordinador de laboratorio de Fitopatologia, Docente",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Laboratorista fitopatología y sanidad vegetal.",
    correo: "phernandez@unag.edu.hn",
  },
  {
    nombreCompleto: "Jorge Rolando Salgado Gómez",
    nombre: "Jorge",
    apellido: "Salgado",
    cargo: "Docente",
    grado: "M.Sc Gerencia de Proyectos de desarrollo",
    area: "Área de desempeño profesional: Topografía, construcciones rurales.",
    correo: "jrsalgadogomez@unag.edu.hn",
  },
  {
    nombreCompleto: "Duglas Augusto Irías Hernández",
    nombre: "Duglas",
    apellido: "Irías",
    cargo: "Docente",
    grado: "Licenciado en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Docencia.",
    correo: "",
  },
  {
    nombreCompleto: "Fany Waleska Medina Hernández",
    nombre: "Fany",
    apellido: "Medina",
    cargo: "Secretaria Ejecutiva de la Coordinación Académica",
    grado: "Licenciada en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Secretaría.",
    correo: "",
  },
  {
    nombreCompleto: "Julia Ondina Bustillo Rosales",
    nombre: "Julia",
    apellido: "Bustillo",
    cargo: "Secretaria Ejecutiva de la decanatura",
    grado: "",
    area: "Área de desempeño profesional: Secretaría.",
    correo: "",
  },
  {
    nombreCompleto: "Daniel Josué Ortiz Martínez",
    nombre: "Daniel",
    apellido: "Ortiz",
    cargo: "Cargo Administrativo",
    grado: "Lic. en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Administración.",
    correo: "",
  },
  {
    nombreCompleto: "Kelin yojana Mondragón Casco",
    nombre: "Kelin",
    apellido: "Mondragón",
    cargo: "Asistente Administrativa del departamento de Producción Vegetal",
    grado: "Licenciada en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Administrativa.",
    correo: "",
  },
  {
    nombreCompleto: "Rosa Hilda Rivera Murillo",
    nombre: "Rosa",
    apellido: "Rivera",
    cargo: "Secretaria del departamento de Ingeniería Agrícola",
    grado: "",
    area: "Área de desempeño profesional: Secretaría.",
    correo: "",
  },
  {
    nombreCompleto: "Saady Humberto Argeñal Godoy",
    nombre: "Saady",
    apellido: "Argeñal",
    cargo: "Tecnico Agricola, Asistente de la Sección de Estación Experimental",
    grado: "Licenciado en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Técnico Agrícola.",
    correo: "",
  },
];

export default docentesCarreraAgronomica;