import type { Docente } from "@/types/docente";

const docentesCarreraRecursosNaturales : Docente[] = [
  {
    nombreCompleto: "Emilio Javier Fuentes Zuniga",
    nombre: "Emilio",
    apellido: "Fuentes",
    cargo: "Decano de Facultad",
    grado: "M.Sc. en Suelos",
    area: "Área de desempeño profesional: Conservación y fertilidad de suelos. Educación Ambiental.",
    correo: "efuentes@unag.edu.hn",
  },
  {
    nombreCompleto: "Jose Adolfo Pineda Roque",
    nombre: "Jose",
    apellido: "Pineda",
    cargo: "Coordinador de la Carrera",
    grado: "Ing. Recursos Naturales y Ambiente",
    area: "Área de desempeño profesional: Sistemas de Producción Sostenible. Energías Renovables.",
    correo: "apineda@unag.edu.hn",
  },
  {
    nombreCompleto: "Noelia Tomasa Larios Bojórquez",
    nombre: "Noelia",
    apellido: "Larios",
    cargo: "Jefa del Departamento Académico de Desarrollo Rural y Agroecología",
    grado: "M.Sc. en Economía Desarrollo y Cambio Climático",
    area: "Área de desempeño profesional: Economía ambiental y Gestión del desarrollo.",
    correo: "nlarios@unag.edu.hn",
  },
  {
    nombreCompleto: "Mario Edgardo Talavera Sevilla",
    nombre: "Mario",
    apellido: "Talavera",
    cargo: "Docente",
    grado: "Ph.D. en Ciencias Sociales, orientación en Gestión del Desarrollo",
    area: "Área de desempeño profesional: Sistemas de Producción Sostenible y Desarrollo Rural. Fitopatología.",
    correo: "mtalavera@unag.edu.hn",
  },
  {
    nombreCompleto: "Jorge Orbin Cardona Hernández",
    nombre: "Jorge",
    apellido: "Cardona",
    cargo: "Jefe del Departamento Académico de Ciencias Hidrometeorológicas",
    grado: "M.Sc. en Ingeniería Ambiental",
    area: "Área de desempeño profesional: Manejo de cuencas hidrográficas y calidad de aguas. Educación Ambiental.",
    correo: "jcardona@unag.edu.hn",
  },
  {
    nombreCompleto: "Oscar Iván Ferreira Catrileo",
    nombre: "Oscar",
    apellido: "Ferreira",
    cargo: "Jefe Departamento de Bosques y Biodiversidad",
    grado: "M.Sc. en Ciencias Agrarias con énfasis en Suelos",
    area: "Área de desempeño profesional: Manejo de Bosques y Viveros Forestales. Sistemas agroforestales.",
    correo: "oferreira@unag.edu.hn",
  },
  {
    nombreCompleto: "Juan Pablo Suazo Euceda",
    nombre: "Juan",
    apellido: "Suazo",
    cargo: "Secretario de la Facultad de Ciencias de la Tierra y la Conservación",
    grado: "M.Sc. en Conservación y Manejo de Vida Silvestre",
    area: "Área de desempeño profesional: Conservación y Manejo de la Biodiversidad. Redacción técnica y científica. Bibliotecología.",
    correo: "jsuazo@unag.edu.hn",
  },
  {
    nombreCompleto: "Ana Mireya Suazo Suazo",
    nombre: "Ana",
    apellido: "Suazo",
    cargo: "Docente",
    grado: "M.Sc. en Manejo y Conservación de la Biodiversidad",
    area: "Área de desempeño profesional: Gestión Ambiental y Cambio climático. Género y desarrollo.",
    correo: "asuazo@unag.edu.hn",
  },
  {
    nombreCompleto: "Blanca Elena Moradel Ortiz",
    nombre: "Blanca",
    apellido: "Moradel",
    cargo: "Docente",
    grado: "Licenciada en Recursos Naturales y Ambiente",
    area: "Área de desempeño profesional: Educación Ambiental y Ecología aplicada.",
    correo: "bmoradel@unag.edu.hn",
  },
  {
    nombreCompleto: "Erlin Vianney Escoto Valladares",
    nombre: "Erlin",
    apellido: "Escoto",
    cargo: "Docente",
    grado: "M.Sc. en Gestión Ambiental de Sistemas Hídricos",
    area: "Área de desempeño profesional: Sistemas de Información Geográfica y Manejo de Cuencas. Agroclimatología.",
    correo: "eescoto@unag.edu.hn",
  },
  {
    nombreCompleto: "Gerardo Humberto Mencía Meza",
    nombre: "Gerardo",
    apellido: "Mencía",
    cargo: "Docente",
    grado: "M.Sc. en Suelos",
    area: "Área de desempeño profesional: Conservación, Fertilidad y contaminación de suelos.",
    correo: "gmencía@unag.edu.hn",
  },
  {
    nombreCompleto: "Gerardo Jair Lagos Hernández",
    nombre: "Gerardo",
    apellido: "Lagos",
    cargo: "Docente",
    grado: "M.Sc. en Economía y Planificación del Desarrollo",
    area: "Área de desempeño profesional: Gestión del Desarrollo. Diseño de proyectos Ambientales.",
    correo: "glagos@unag.edu.hn",
  },
  {
    nombreCompleto: "Jorge David Zúniga Mejía",
    nombre: "Jorge",
    apellido: "Zúniga",
    cargo: "Docente",
    grado: "M.Sc. en Manejo de Bosques y Conservación de la Biodiversidad",
    area: "Área de desempeño profesional: Manejo de bosques. Sistemas agroforestales.",
    correo: "jzuniga@unag.edu.hn",
  },
  {
    nombreCompleto: "Jorge Luis Escobar",
    nombre: "Jorge",
    apellido: "Escobar",
    cargo: "Docente",
    grado: "M.Sc. en Economía Desarrollo y Cambio Climático",
    area: "Área de desempeño profesional: Gestión ambiental y Economía de los Recursos Naturales.",
    correo: "jescobar@unag.edu.hn",
  },
  {
    nombreCompleto: "José Adolfo Pineda Roque",
    nombre: "José",
    apellido: "Pineda",
    cargo: "Docente",
    grado: "M.Sc. en Gestión de Energías Renovables",
    area: "Área de desempeño profesional: Sistemas de Producción Sostenible. Energías Renovables.",
    correo: "jpineda@unag.edu.hn",
  },
  {
    nombreCompleto: "José Bayardo Alemán Mejía",
    nombre: "José",
    apellido: "Alemán",
    cargo: "Docente",
    grado: "M.Sc. en Manejo y Conservación de Bosques Tropicales y Biodiversidad",
    area: "Área de desempeño profesional: Manejo y Conservación de la Biodiversidad. Manejo de áreas protegidas.",
    correo: "jaleman@unag.edu.hn",
  },
  {
    nombreCompleto: "José Trinidad Reyes Sandoval",
    nombre: "José",
    apellido: "Reyes",
    cargo: "Docente",
    grado: "M.Sc. en Ciencias Agrarias, énfasis en Suelos",
    area: "Área de desempeño profesional: Ciencias del suelo, Estadística, Diseños experimentales.",
    correo: "jreyes@unag.edu.hn",
  },
  {
    nombreCompleto: "Josué David Matute Aguilar",
    nombre: "Josué",
    apellido: "Matute",
    cargo: "Docente",
    grado: "M.Sc. Scientiae en Desarrollo Rural",
    area: "Área de desempeño profesional: Sistemas de Producción Sostenible y Desarrollo Rural. Metodologías de Extensión.",
    correo: "jmatute@unag.edu.hn",
  },
  {
    nombreCompleto: "Oscar Ovidio Redondo Flores",
    nombre: "Oscar",
    apellido: "Redondo",
    cargo: "Docente",
    grado: "M.Sc. en Suelos",
    area: "Área de desempeño profesional: Ciencias del suelo, Estadística, Diseños experimentales.",
    correo: "oredondo@unag.edu.hn",
  },
  {
    nombreCompleto: "Ramón León Canaca Calderón",
    nombre: "Ramón",
    apellido: "Canaca",
    cargo: "Docente",
    grado: "M.Sc. en Ciencias con especialidad en Hidrociencias",
    area: "Área de desempeño profesional: Manejo integrado de cuencas y ordenamiento territorial. Teledetección.",
    correo: "rcanaca@unag.edu.hn",
  },
  {
    nombreCompleto: "Selvin Antonio Saravia Maldonado",
    nombre: "Selvin",
    apellido: "Saravia",
    cargo: "Docente",
    grado: "M.Sc. en Agronomía",
    area: "Área de desempeño profesional: Fertilidad y conservación de Suelos.",
    correo: "ssaravia@unag.edu.hn",
  },
  {
    nombreCompleto: "Wendy Leonela Castellanos Valerio",
    nombre: "Wendy",
    apellido: "Castellanos",
    cargo: "Docente",
    grado: "M.Sc. Scientiae en Agricultura Ecológica",
    area: "Área de desempeño profesional: Agricultura ecológica y producción orgánica. Estadística.",
    correo: "wcastellanos@unag.edu.hn",
  },
];

export default docentesCarreraRecursosNaturales;