import type { PersonalSedeRegional, PersonalDocenteArea } from "@/types/personal-sede-regional";

export const estructuraAdministrativa: PersonalSedeRegional[] = [
  {
    nombreCompleto: "Carmen Elena Barahona Domínguez",
    nombre: "Carmen",
    apellido: "Barahona",
    cargo: "Directora Centro Regional Comayagua",
    correo: "cbarahona@unag.edu.hn",
  },
  {
    nombreCompleto: "José Dagoberto Vega Figueroa",
    nombre: "José",
    apellido: "Vega",
    cargo: "Coordinador Académico",
    correo: "jvega@unag.edu.hn",
  },
  {
    nombreCompleto: "Euclides Romero Guevara Aguilar",
    nombre: "Euclides",
    apellido: "Guevara",
    cargo: "Secretario Regional Comayagua",
    correo: "eguevara@unag.edu.hn",
  },
  {
    nombreCompleto: "Kennia Lizeth Valladares Mejía",
    nombre: "Kennia",
    apellido: "Valladares",
    cargo: "Administradora Regional",
    correo: "klvalladares@unag.edu.hn",
  },
  {
    nombreCompleto: "Wilmer Omar Rios Valladarez",
    nombre: "Wilmer",
    apellido: "Rios",
    cargo: "Coordinador de Investigación",
    correo: "wrios@unag.edu.hn",
  },
  {
    nombreCompleto: "Carlos Fernando Miranda Marcía",
    nombre: "Carlos",
    apellido: "Miranda",
    cargo: "Coordinador de Vinculación",
    correo: "cmiranda@unag.edu.hn",
  },
  {
    nombreCompleto: "Andrea Cecilia Molina Padilla",
    nombre: "Andrea",
    apellido: "Molina",
    cargo: "Coordinadora de Vida Estudiantil",
    correo: "amomolina@unag.edu.hn",
  },
  {
    nombreCompleto: "Darling Margarita Castro Canales",
    nombre: "Darling",
    apellido: "Castro",
    cargo: "Coordinadora de Internacionalización",
    correo: "dcastros@unag.edu.hn",
  },
  {
    nombreCompleto: "Estela Yamileth Aguilar Alvarez",
    nombre: "Estela",
    apellido: "Aguilar",
    cargo: "Coordinadora de Estudios Generales",
    correo: "eyaguilar@unag.edu.hn",
  },
  {
    nombreCompleto: "Manuel de Jesús Maldonado",
    nombre: "Manuel",
    apellido: "Maldonado",
    cargo: "Coordinador de Ciencias Económicas y Administrativas",
    correo: "mmaldonado@unag.edu.hn",
  },
  {
    nombreCompleto: "Ivis Flores",
    nombre: "Ivis",
    apellido: "Flores",
    cargo: "Gerente de Producción y Comercialización",
    correo: "igflores@unag.edu.hn",
  },
  {
    nombreCompleto: "Alison Samantha Zelaya",
    nombre: "Alison",
    apellido: "Zelaya",
    cargo: "Comercialización",
    correo: "azelaya@unag.edu.hn",
  },
  {
    nombreCompleto: "Gabriela Suyapa Hernández Casco",
    nombre: "Gabriela",
    apellido: "Hernández",
    cargo: "Coordinadora de Ingeniería Agronómica",
    correo: "ghernan@unag.edu.hn",
  },
  {
    nombreCompleto: "Nolvia Esperanza Ruiz",
    nombre: "Nolvia",
    apellido: "Ruiz",
    cargo: "Biblioteca",
    correo: "nruiz@unag.edu.hn",
  },
  {
    nombreCompleto: "José Trinidad Reyes Medina",
    nombre: "José",
    apellido: "Reyes",
    cargo: "Encargado Regional de SETIC",
    correo: "setic.comayagua@unag.edu.hn",
  },
  {
    nombreCompleto: "Wendy Elizabeth Cerrato Altamirano",
    nombre: "Wendy",
    apellido: "Cerrato",
    cargo: "Coordinadora del Área de Producción Vegetal",
    correo: "coordinacion.vegetal.comayagua@unag.edu.hn",
  },
  {
    nombreCompleto: "Delia Dixiana Molina Martínez",
    nombre: "Delia",
    apellido: "Molina",
    cargo: "Coordinadora del Área de Producción Animal",
    correo: "coordinacion.animal.comayagua@unag.edu.hn",
  },
];

export const personalDocente: PersonalDocenteArea[] = [
  {
    area: "Coordinación de Estudios Generales",
    docentes: [
      "Estela Yamileth Aguilar Álvarez",
      "Carlos Fernando Miranda Marcía",
      "Fany Sobeida Villafranca Rivera",
      "José Dagoberto Vega Figueroa",
      "Darling Margarita Castro Canales",
      "Lijia Patricia Carrillo Alfaro",
    ],
  },
  {
    area: "Coordinación de Ciencias Económicas y Administrativas",
    docentes: [
      "Kennia Lizeth Valladares Mejía",
      "Carmen Elena Barahona Domínguez",
      "Euclides Romero Guevara Aguilar",
      "Marco Antonio Hernández Bárcenas",
      "Manuel de Jesús Maldonado",
      "Nahún Gerardo Salinas Díaz",
    ],
  },
  {
    area: "Coordinación de Producción Animal",
    docentes: [
      "Delia Dixiana Molina Martínez",
      "Dalwin Salvador Guillen Hernández",
      "Sobeyda Carolina Reyes Robles",
    ],
  },
  {
    area: "Coordinación de Producción Vegetal",
    docentes: [
      "Wendy Elizabeth Cerrato Altamirano",
      "Gabriela Suyapa Hernández Casco",
      "Walter Danilo Maradiaga Rodríguez",
      "Pedro Cáceres Martínez",
    ],
  },
];
