import type { Docente } from "@/types/docente";

const docentesFacultadMedicinaVeterinaria : Docente[] = [
 
  {
    nombreCompleto: "Francisco Antonio Barahona Montalvan",
    nombre: "Francisco",
    apellido: "Barahona",
    cargo: "Decano de la Facultad",
    grado: "",
    area: "Área de desempeño profesional: Avicultura",
    correo: "",
  },
  {
    nombreCompleto: "Ruben Ramirez Aquino",
    nombre: "Ruben",
    apellido: "Ramirez",
    cargo: "Coordinador de la Carrera de Medicina Veterinaria",
    grado: "Dr. En Medicina Veterinaria",
    area: "Área de desempeño profesional: Docencia e investigación, promocion del bienestar animal",
    correo: "",
  },
  {
    nombreCompleto: "Josué Omar Mendoza Montoya",
    nombre: "Josué",
    apellido: "Mendoza",
    cargo: "Jefatura del DGPA",
    grado: "Ingeniero Agrónomo",
    area: "",
    correo: "",
  },
  {
    nombreCompleto: "Kenny Sirey Nájera Aparicio",
    nombre: "Kenny",
    apellido: "Nájera",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Pastos y Forrajes/ vinculación",
    correo: "",
  },
  {
    nombreCompleto: "Rober Danilo Rubí",
    nombre: "Rober",
    apellido: "Rubí",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Pastos y Forrajes/ vinculación",
    correo: "",
  },
  {
    nombreCompleto: "Angie Yamalith Canelas Escobar",
    nombre: "Angie",
    apellido: "Canelas",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Caprino Ovino y Ovejos",
    correo: "",
  },
  {
    nombreCompleto: "Héctor Leonel Alvarado",
    nombre: "Héctor",
    apellido: "Alvarado",
    cargo: "",
    grado: "M.Sc. Zootecnia en Nutrición Animal",
    area: "Área de desempeño profesional: Alimentación y Nutrición Animal. Seminario de investigación",
    correo: "",
  },
  {
    nombreCompleto: "Henris Jobany Morazán Nuñez",
    nombre: "Henris",
    apellido: "Morazán",
    cargo: "",
    grado: "Ph. D. en Ciencia y Tecnología Agraria y Alimentaria",
    area: "Área de desempeño profesional: Nutricion Animal",
    correo: "",
  },
  {
    nombreCompleto: "Julio San Martin Cálix",
    nombre: "Julio",
    apellido: "San Martin",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Apicultura",
    correo: "",
  },
  {
    nombreCompleto: "Reina Maribel Sierra Fernandez",
    nombre: "Reina",
    apellido: "Sierra",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Apicultura",
    correo: "",
  },
  {
    nombreCompleto: "Oscar Ernesto Castellanos Sosa",
    nombre: "Oscar",
    apellido: "Castellanos",
    cargo: "",
    grado: "Licenciado en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Apicultura",
    correo: "",
  },
  {
    nombreCompleto: "Mario Roberto Hernández Cubas",
    nombre: "Mario",
    apellido: "Hernández",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Acuacultura",
    correo: "",
  },
  {
    nombreCompleto: "Santos Marcelino Espinal Valladares",
    nombre: "Santos",
    apellido: "Espinal",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Producción y Comercialización",
    correo: "",
  },
  {
    nombreCompleto: "Benito Esaú Pereira",
    nombre: "Benito",
    apellido: "Pereira",
    cargo: "",
    grado: "M. Sc. en Administración de empresas",
    area: "Área de desempeño profesional: Laboratorio de la Ciencia de la Carne",
    correo: "",
  },
  {
    nombreCompleto: "Keysi Patricia Diaz Aguilera",
    nombre: "Keysi",
    apellido: "Diaz",
    cargo: "",
    grado: "Tecnologia de Alimentos",
    area: "Área de desempeño profesional: Laboratorio de la Ciencia de la Carne",
    correo: "",
  },
  {
    nombreCompleto: "Dina Marlen Castro Mejía",
    nombre: "Dina",
    apellido: "Castro",
    cargo: "",
    grado: "M.Sc. Gestión de la Calidad Total, Universidad Católica de Honduras. Médico Veterinario, Universidad Federal Santa Maria RS Brasil",
    area: "Área de desempeño profesional: Enfermedades Infectocontagiosas, Etología y bienestar animal",
    correo: "",
  },
  {
    nombreCompleto: "Ventura Obdulio Zelaya",
    nombre: "Ventura",
    apellido: "Zelaya",
    cargo: "",
    grado: "M.Sc. en Gerencia de Proyectos de Desarrollo",
    area: "Área de desempeño profesional: Proyectos",
    correo: "",
  },
  {
    nombreCompleto: "Licza Rosibel Padilla Salgado",
    nombre: "Licza",
    apellido: "Padilla",
    cargo: "",
    grado: "M. Sc Nutricion Animal",
    area: "Área de desempeño profesional: Vicerrectoría academica",
    correo: "",
  },
  {
    nombreCompleto: "Rubén Augusto Sinclair Guitiérrez",
    nombre: "Rubén",
    apellido: "Sinclair",
    cargo: "",
    grado: "M.Sc. Gerencia de proyectos de Desarrollo",
    area: "Área de desempeño profesional: Pastos y Forrajes Universidad-Sociedad",
    correo: "",
  },
  {
    nombreCompleto: "Grace Marlene Carvajal",
    nombre: "Grace",
    apellido: "Carvajal",
    cargo: "",
    grado: "M. Sc. Ciencias Veterinarias",
    area: "",
    correo: "",
  },
  {
    nombreCompleto: "Belia Maria Suazo Martinez",
    nombre: "Belia",
    apellido: "Suazo",
    cargo: "",
    grado: "M.Sc. en Economia y Desarrollo",
    area: "Área de desempeño profesional: Acuacultura",
    correo: "",
  },
  {
    nombreCompleto: "Fran Humberto Zúniga Meza",
    nombre: "Fran",
    apellido: "Zúniga",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Avicultura",
    correo: "",
  },
  {
    nombreCompleto: "Gustavo Alonso Ardón",
    nombre: "Gustavo",
    apellido: "Ardón",
    cargo: "",
    grado: "Ph.D. Economia Empresarial",
    area: "Área de desempeño profesional: Avicultura",
    correo: "",
  },
  {
    nombreCompleto: "Jhony Leonel Barahona Montalvan",
    nombre: "Jhony",
    apellido: "Barahona",
    cargo: "",
    grado: "M.Sc. en Administración de Empresas",
    area: "Área de desempeño profesional: Centro de Produccion Porcina",
    correo: "",
  },
  {
    nombreCompleto: "Javier Antonio Reyes Luna",
    nombre: "Javier",
    apellido: "Reyes",
    cargo: "",
    grado: "MSc Formulación y evaluacion de proyectos",
    area: "Área de desempeño profesional: Caprino Ovino y Ovejos",
    correo: "",
  },
  {
    nombreCompleto: "Miguel Angel Garcia Mejía",
    nombre: "Miguel",
    apellido: "Garcia",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Produccion Porcina",
    correo: "",
  },
  {
    nombreCompleto: "Gerson Antonio Acosta Bonilla",
    nombre: "Gerson",
    apellido: "Acosta",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "Área de desempeño profesional: Produccion Porcina",
    correo: "",
  },
  {
    nombreCompleto: "José Angel Acosta",
    nombre: "José",
    apellido: "Acosta",
    cargo: "",
    grado: "Ingeniero Agrónomo",
    area: "",
    correo: "",
  },
  {
    nombreCompleto: "Valeria Estefania Cerrato Castellanos",
    nombre: "Valeria",
    apellido: "Cerrato",
    cargo: "",
    grado: "Médico Veterinario, Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Anatomía Comparada. Patología aviar",
    correo: "",
  },
  {
    nombreCompleto: "Yahaira Marlen Hernández López",
    nombre: "Yahaira",
    apellido: "Hernández",
    cargo: "",
    grado: "Médico Veterinario, Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Propedéutica (aves). Patología Veterinaria. Patología Quirúrgica",
    correo: "",
  },
  {
    nombreCompleto: "Marvin Orlando García Aguilar",
    nombre: "Marvin",
    apellido: "García",
    cargo: "",
    grado: "Médico Veterinario, Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Medicina de Fauna Silvestre. Patología Acuícola",
    correo: "",
  },
  {
    nombreCompleto: "Eduardo Aguilar",
    nombre: "Eduardo",
    apellido: "Aguilar",
    cargo: "",
    grado: "Médico Veterinario, Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Anatomía Veterinaria. Inspección de bienes de origen animal",
    correo: "",
  },
  {
    nombreCompleto: "David Antonio Cantarero Peralta",
    nombre: "David",
    apellido: "Cantarero",
    cargo: "Jefe de Departamento Académico Morfología",
    grado: "Médico Veterinario Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Fisiología Veterinaria Propedéutica (animales de compañía)",
    correo: "",
  },
  {
    nombreCompleto: "Orlando José Castillo Rosa",
    nombre: "Orlando",
    apellido: "Castillo",
    cargo: "",
    grado: "M. Sc. Ciencias Veterinarias",
    area: "Área de desempeño profesional: Pastos y Forrajes",
    correo: "",
  },
  {
    nombreCompleto: "Carlos Manuel Ulloa Ulloa",
    nombre: "Carlos",
    apellido: "Ulloa",
    cargo: "",
    grado: "Ph.D. Ciencia Animal",
    area: "Área de desempeño profesional: Centro de Produccion Porcina",
    correo: "",
  },
  {
    nombreCompleto: "Harin Joel Mejia Castilla",
    nombre: "Harin",
    apellido: "Mejia",
    cargo: "",
    grado: "M. Sc. en Educación Rural y Desarrollo",
    area: "Área de desempeño profesional: Bovinoctia",
    correo: "",
  },
  {
    nombreCompleto: "Marvin Noé Flores Sánchez",
    nombre: "Marvin",
    apellido: "Flores",
    cargo: "",
    grado: "M.Sc. en Producción Agropecuaria con opción terminal en el área Pecuaria",
    area: "Área de desempeño profesional: Bovinoctia",
    correo: "",
  },
  {
    nombreCompleto: "Josselin Maryeri Brizo Murillo",
    nombre: "Josselin",
    apellido: "Brizo",
    cargo: "",
    grado: "Médico Veterinario, Universidad Nacional de Agricultura. M.Sc. Ciencia Animal, Universidad San Carlos de Guatemala",
    area: "Área de desempeño profesional: Fisiopatología de la Reproducción y Obstetricia. Biotecnología de la Reproducción",
    correo: "",
  },
  {
    nombreCompleto: "Hector Antonio Diaz Antúnez",
    nombre: "Hector",
    apellido: "Diaz",
    cargo: "",
    grado: "M.Sc. en Ciencias agrarias con énfasis en mejoramiento genético y diseños experimentales",
    area: "Área de desempeño profesional: Genética Animal",
    correo: "",
  },
  {
    nombreCompleto: "José Francisco Aguiriano Sánchez",
    nombre: "José",
    apellido: "Aguiriano",
    cargo: "",
    grado: "Médico Veterinario, Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Propedéutica (bovinos y equinos). Salud y Sistemas de Producción",
    correo: "",
  },
  {
    nombreCompleto: "Romeo Uclides Guervara",
    nombre: "Romeo",
    apellido: "Guervara",
    cargo: "",
    grado: "M.Sc. en Reproducción animal",
    area: "Área de desempeño profesional: Centro de Produccion Porcina",
    correo: "",
  },
  {
    nombreCompleto: "Carlos José Cartagena Alvarenga",
    nombre: "Carlos",
    apellido: "Cartagena",
    cargo: "",
    grado: "Médico Veterinario Universidad Nacional de Agricultura",
    area: "Área de desempeño profesional: Clínica de bovinos y Equinos",
    correo: "",
  },
  {
    nombreCompleto: "Kelvin Orlando Espinoza Blandon",
    nombre: "Kelvin",
    apellido: "Espinoza",
    cargo: "",
    grado: "Ciencias Veterinaria",
    area: "",
    correo: "",
  },
  {
    nombreCompleto: "Lisandro Zelaya Bertrand",
    nombre: "Lisandro",
    apellido: "Zelaya",
    cargo: "Jefe Departamento Academico de Medicina Veterinaria",
    grado: "Médico Veterinario, Universidad Federal Santa Maria RS Brasil",
    area: "Área de desempeño profesional: Propedéutica (porcinos). Medicina Interna. Medicina Veterinaria",
    correo: "",
  },
  {
    nombreCompleto: "Fuggy Ernestina Castro",
    nombre: "Fuggy",
    apellido: "Castro",
    cargo: "",
    grado: "Médico Veterinario, Universidad Federal de Porto Alegre RS, Brasil. M.Sc. Nutrición de Monogástricos, Universidad Guelph-Canada",
    area: "Área de desempeño profesional: Ética y Legislación Veterinaria. Patología Apícola",
    correo: "",
  },
  {
    nombreCompleto: "Roger Gustavo Moncada",
    nombre: "Roger",
    apellido: "Moncada",
    cargo: "",
    grado: "Médico Veterinario",
    area: "Área de desempeño profesional: Centro de Produccion Porcina",
    correo: "",
  },
  {
    nombreCompleto: "Osman Alejandro Garcia",
    nombre: "Osman",
    apellido: "Garcia",
    cargo: "",
    grado: "Médico Veterinario Zootecnista, Centro de Estudio Ciudad de Monterrey, Estado de Leon, Mexico",
    area: "Área de desempeño profesional: Políticas Publicas. Medicina Legal",
    correo: "",
  },
  {
    nombreCompleto: "Elfrego Adrián Ponce",
    nombre: "Elfrego",
    apellido: "Ponce",
    cargo: "",
    grado: "Médico Veterinario Zootecnista, Universidad de Guadalajara, México",
    area: "Área de desempeño profesional: Salud Pública Veterinaria. Inspección de bienes de origen animal",
    correo: "",
  },
  {
    nombreCompleto: "Helen Lobo",
    nombre: "Helen",
    apellido: "Lobo",
    cargo: "",
    grado: "Microbióloga Veterinaria, Universidad Nacional Autónoma de Honduras",
    area: "Área de desempeño profesional: Virología Veterinaria. Laboratorio Clínico Veterinario. Epidemiologia Veterinaria",
    correo: "",
  },
  {
    nombreCompleto: "Yennifer Díaz",
    nombre: "Yennifer",
    apellido: "Díaz",
    cargo: "",
    grado: "Microbióloga Veterinaria Universidad Nacional Autónoma de Honduras",
    area: "Área de desempeño profesional: Microbiología Veterinaria. Inmunología Veterinaria",
    correo: "",
  },
];

export default docentesFacultadMedicinaVeterinaria;