import type { Docente } from "@/types/docente";

const docentesFacultadCienciasEconomicas : Docente[] = [
  {
    nombreCompleto: "Neris Yessenia Escobar Ramos",
    nombre: "Neris",
    apellido: "Escobar",
    cargo: "Decana de la Facultad",
    grado: "Maestría en Gestión de Proyectos",
    area: "Área de desempeño profesional: Administración de Empresas",
    correo: "nescobar@unag.edu.hn",
  },
  {
    nombreCompleto: "Karen Evelia Lara",
    nombre: "Karen",
    apellido: "Lara",
    cargo: "Jefe de Depto. Economía Sectorial. Docente",
    grado: "Licenciatura en Mercadotecnia",
    area: "Área de desempeño profesional: Mercadeo Informática Administración",
    correo: "klara@unag.edu.hn",
  },
  {
    nombreCompleto: "Norman Leonel Mercadal Tejada",
    nombre: "Norman",
    apellido: "Mercadal",
    cargo: "Jefe Depto Organización y Dirección Empresarial",
    grado: "M.Sc. en Gerencia de Proyectos de Desarrollo",
    area: "Área de desempeño profesional: Docencia y Comunicación",
    correo: "nmercadal@unag.edu.hn",
  },
  {
    nombreCompleto: "Alex René Dubón",
    nombre: "Alex",
    apellido: "Dubón",
    cargo: "Docente",
    grado: "Maestría en Ciencias",
    area: "Área de desempeño profesional: Tecnologías de Información Economía Agrícola",
    correo: "ardubon@unag.edu.hn",
  },
  {
    nombreCompleto: "Ivonne Paulette Zelaya Bustillo",
    nombre: "Ivonne",
    apellido: "Zelaya",
    cargo: "Docente",
    grado: "MBA en Comercio Internacional, M.Sc. Dirección Empresarial",
    area: "Área de desempeño profesional: Finanzas y Comercio Internacional",
    correo: "izelaya@unag.edu.hn",
  },
  {
    nombreCompleto: "Hariana Melisa Gálvez",
    nombre: "Hariana",
    apellido: "Gálvez",
    cargo: "Asistente Decanatura",
    grado: "Licenciatura en Administración de Empresas Agropecuarias",
    area: "Área de desempeño profesional: Administrativo",
    correo: "hgalvez@unag.edu.hn",
  },
  {
    nombreCompleto: "Miriam Anabel Alvarado",
    nombre: "Miriam",
    apellido: "Alvarado",
    cargo: "Docente",
    grado: "Maestría en Gestión de la Calidad Total",
    area: "Área de desempeño profesional: Economía Agrícola, Administración Agropecuaria y Calidad Total",
    correo: "",
  },
  {
    nombreCompleto: "Leslie Waleska Escobar Sánchez",
    nombre: "Leslie",
    apellido: "Escobar",
    cargo: "Docente",
    grado: "Maestría Gestión Calidad Total, Maestría Economía y Finanzas",
    area: "Área de desempeño profesional: Administrativa, financiera y Económica",
    correo: "wescobar@unag.edu.hn",
  },
  {
    nombreCompleto: "Mariela Alemán Casco",
    nombre: "Mariela",
    apellido: "Alemán",
    cargo: "Docente",
    grado: "Msc. Gerencia en Formulación y Evaluación de Proyectos",
    area: "Área de desempeño profesional: Docencia/Miembro Junta de Dirección Universitaria/Comité de PPS/Asesora de Tesis, Práctica Profesional Supervisada",
    correo: "maleman@unag.edu.hn",
  },
  {
    nombreCompleto: "Francisco Javier Medina",
    nombre: "Francisco",
    apellido: "Medina",
    cargo: "Técnico Docente",
    grado: "M.Sc. en Educación Superior y M.Sc. en Economía Ambiental y Administración de los RRNN",
    area: "Área de desempeño profesional: Economía Agrícola, Formulación de Proyectos Agropecuarios, Economía Ambiental",
    correo: "",
  },
  {
    nombreCompleto: "José Luis Castillo",
    nombre: "José",
    apellido: "Castillo",
    cargo: "Docente investigador",
    grado: "Maestría en Gerencia de Proyectos",
    area: "Área de desempeño profesional: Formulación de proyectos, extensión agrícola, investigación y desarrollo comunitario",
    correo: "jcastillo@unag.edu.hn",
  },
  {
    nombreCompleto: "Mariano Enrique Guillén Moreno",
    nombre: "Mariano",
    apellido: "Guillén",
    cargo: "Docente",
    grado: "Ing. Agrónomo",
    area: "Área de desempeño profesional: Administración de Empresas",
    correo: "mguillen@unag.edu.hn",
  },
  {
    nombreCompleto: "Mauricio Alberto Moreno Escobar",
    nombre: "Mauricio",
    apellido: "Moreno",
    cargo: "Docente Secretario de la Facultad",
    grado: "Maestría en Gerencia de Proyectos de Desarrollo",
    area: "Área de desempeño profesional: Administración de Empresas, Proyectos, Emprendimiento Desarrollo Local",
    correo: "mmoreno@unag.edu.hn",
  },
  {
    nombreCompleto: "Tony Dester Escobar Sánchez",
    nombre: "Tony",
    apellido: "Escobar",
    cargo: "Docente",
    grado: "Lic. en Administración Pública y Lic. Informática Educativa",
    area: "Área de desempeño profesional: Informática, Contabilidad de Costos",
    correo: "lescobar@unag.edu.hn",
  },
];

export default docentesFacultadCienciasEconomicas;