import type { Docente } from "@/types/docente";

const docentesFacultadCienciasTecnologicas : Docente[] = [
  {
    nombreCompleto: "Mario José Gonzales Santos",
    nombre: "Mario",
    apellido: "Gonzales",
    cargo: "Decano de la Facultad de Ciencias Tecnológicas",
    grado: "M.Sc. en Ciencia e Ingeniería en Alimentos",
    area: "Área de desempeño profesional: Ingeniería de Alimentos (Tecnologías emergentes y deshidratación).",
    correo: "mgonzales@unag.edu.hn",
  },
  {
    nombreCompleto: "Héctor Alonzo Gómez Gómez",
    nombre: "Héctor",
    apellido: "Gómez",
    cargo: "Profesor Titular III / Jefe de Departamento",
    grado: "Ph.D. en Horticultura",
    area: "Área de desempeño profesional: Compuestos Bioactivos (Fitoquímica).",
    correo: "hgomez@unag.edu.hn",
  },
  {
    nombreCompleto: "Zoila Esperanza Flores Hernández",
    nombre: "Zoila",
    apellido: "Flores",
    cargo: "Profesor Titular I",
    grado: "M.Sc. en Ciencia e Ingeniería en Alimentos",
    area: "Área de desempeño profesional: Ingeniería de Alimentos.",
    correo: "",
  },
  {
    nombreCompleto: "Arlin Daneri Lobo Medina",
    nombre: "Arlin",
    apellido: "Lobo",
    cargo: "Profesor Titular II / Secretario de Facultad",
    grado: "M.Sc. en Seguridad Alimentaria y Nutricional",
    area: "Área de desempeño profesional: Seguridad Alimentaria. Procesamiento Acuícola y Acuacultura.",
    correo: "alobo@unag.edu.hn",
  },
  {
    nombreCompleto: "Gladis María Guevara Padilla",
    nombre: "Gladis",
    apellido: "Guevara",
    cargo: "Profesor Titular II / Coordinadora de Carrera",
    grado: "M.Sc. en Nutrición y Biotecnología Alimentaria",
    area: "Área de desempeño profesional: Nutrición y Biotecnología Alimentaria.",
    correo: "gguevara@unag.edu.hn",
  },
  {
    nombreCompleto: "Pablo Antonio Pérez Salinas",
    nombre: "Pablo",
    apellido: "Pérez",
    cargo: "Profesor Titular I / Administrador FCT",
    grado: "M.Sc. en Sistemas de Gestión de Calidad Integrados",
    area: "Área de desempeño profesional: Organización y gestión de la integración de sistemas de calidad, medio ambiente y seguridad ocupacional.",
    correo: "pperez@unag.edu.hn",
  },
  {
    nombreCompleto: "Emerson Josué Martínez Jiménez",
    nombre: "Emerson",
    apellido: "Martínez",
    cargo: "Profesor Titular II",
    grado: "",
    area: "Área de desempeño profesional: Procesamiento y conservación de granos y cereales. Seguridad alimentaria y nutricional.",
    correo: "",
  },
  {
    nombreCompleto: "Francisco Enrique Sánchez Rosales",
    nombre: "Francisco",
    apellido: "Sánchez",
    cargo: "Profesor Titular II",
    grado: "",
    area: "Área de desempeño profesional: Producción y Escalamiento de cultivos celulares aeróbicos en biorreactores.",
    correo: "fsanchez@unag.edu.hn",
  },
  {
    nombreCompleto: "Loren Paola Macias Bu",
    nombre: "Loren",
    apellido: "Macias",
    cargo: "Profesor Titular I",
    grado: "",
    area: "Área de desempeño profesional: Procesamiento de Alimentos.",
    correo: "lmacias@unag.edu.hn",
  },
  {
    nombreCompleto: "Nairoby Sevila Cardoso",
    nombre: "Nairoby",
    apellido: "Sevila",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Seguridad alimentaria, análisis de los alimentos.",
    correo: "nsevila@unag.edu.hn",
  },
  {
    nombreCompleto: "Wilson Alexander Martínez Martínez",
    nombre: "Wilson",
    apellido: "Martínez",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Bioprocesos.",
    correo: "wmartinez@unag.edu.hn",
  },
  {
    nombreCompleto: "Lidia Magdalena Díaz Pineda",
    nombre: "Lidia",
    apellido: "Díaz",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Frutas y Hortalizas.",
    correo: "ldiaz@unag.edu.hn",
  },
  {
    nombreCompleto: "Jaime Onán Salgado Mejía",
    nombre: "Jaime",
    apellido: "Salgado",
    cargo: "Profesor Titular III / Jefe de Departamento Académico",
    grado: "M.Sc. en Procesamiento de Alimentos",
    area: "Área de desempeño profesional: Ingeniería de alimentos.",
    correo: "jasalgado@unag.edu.hn",
  },
  {
    nombreCompleto: "Rosa Arelys Betancourth Raudales",
    nombre: "Rosa",
    apellido: "Betancourth",
    cargo: "Profesor Titular I",
    grado: "",
    area: "Área de desempeño profesional: Análisis sensorial de alimentos, Diseño de plantas, Aditivos Alimentarios, Procesamiento de Carnes y productos acuícolas.",
    correo: "abetancourth@unag.edu.hn",
  },
  {
    nombreCompleto: "Olvin Steve Rosales Menjívar",
    nombre: "Olvin",
    apellido: "Rosales",
    cargo: "Profesor Titular I",
    grado: "",
    area: "Área de desempeño profesional: Ingeniería Industrial.",
    correo: "orosales@unag.edu.hn",
  },
  {
    nombreCompleto: "Katy Marcela Castellanos Reyes",
    nombre: "Katy",
    apellido: "Castellanos",
    cargo: "Profesor Titular I",
    grado: "",
    area: "Área de desempeño profesional: Procesamiento de Alimentos.",
    correo: "kcastellanos@unag.edu.hn",
  },
  {
    nombreCompleto: "Ramón Antonio Herrera Antúnez",
    nombre: "Ramón",
    apellido: "Herrera",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Ciencia de los Granos y Cereales.",
    correo: "rherrera@unag.edu.hn",
  },
  {
    nombreCompleto: "Jhunior Abrahan Marcía Fuentes",
    nombre: "Jhunior",
    apellido: "Marcía",
    cargo: "Profesor Titular II",
    grado: "M.Sc. en Procesamiento de Alimentos",
    area: "Área de desempeño profesional: Ingeniería de alimentos.",
    correo: " jmarcia@unag.edu.hn",
  },
  {
    nombreCompleto: "Keisy Bianey Peralta Matute",
    nombre: "Keisy",
    apellido: "Peralta",
    cargo: "Profesor Titular I",
    grado: "",
    area: "Área de desempeño profesional: Organización y gestión de la integración de sistemas de calidad, medio ambiente y seguridad ocupacional.",
    correo: "",
  },
  {
    nombreCompleto: "Fanny Aleyda Maradiaga",
    nombre: "Fanny",
    apellido: "Maradiaga",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Inocuidad y calidad de alimentos.",
    correo: "",
  },
  {
    nombreCompleto: "Javier Osaias Betancourth Raudales",
    nombre: "Javier",
    apellido: "Betancourth",
    cargo: "Profesor Titular I",
    grado: "",
    area: "Área de desempeño profesional: Ingeniería de Alimentos.",
    correo: "",
  },
  {
    nombreCompleto: "Débora Karolina Mejía Méndez",
    nombre: "Débora",
    apellido: "Mejía",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Productos lácteos.",
    correo: "",
  },
  {
    nombreCompleto: "Luis José Castillo Rodríguez",
    nombre: "Luis",
    apellido: "Castillo",
    cargo: "Profesor Titular II",
    grado: "",
    area: "Área de desempeño profesional: Procesamiento de lácteos y derivados.",
    correo: "",
  },
  {
    nombreCompleto: "Carlos Orlando Inestroza Lizardo",
    nombre: "Carlos",
    apellido: "Inestroza",
    cargo: "Profesor Titular III",
    grado: "Ph.D. en Producción Vegetal",
    area: "Área de desempeño profesional: Poscosecha de Frutas y Hortalizas.",
    correo: "cinestroza@unag.edu.hn",
  },
  {
    nombreCompleto: "Ledy Yolany Nájera Aparicio",
    nombre: "Ledy",
    apellido: "Nájera",
    cargo: "Profesor Asistente",
    grado: "",
    area: "Área de desempeño profesional: Procesamiento de lácteos.",
    correo: "",
  },
  {
    nombreCompleto: "Mildre Eleazar Turcios Rivera",
    nombre: "Mildre",
    apellido: "Turcios",
    cargo: "Profesor Titular III",
    grado: "",
    area: "Área de desempeño profesional: Procesamiento de frutas y Hortalizas.",
    correo: "",
  },
  {
    nombreCompleto: "Alba Julia Muñoz",
    nombre: "Alba",
    apellido: "Muñoz",
    cargo: "Profesor Titular III",
    grado: "M.Sc. En Gestión de la Calidad Total",
    area: "Área de desempeño profesional: Gestión de la calidad Total.",
    correo: "amuñoz@unag.edu.hn",
  },
];

export default docentesFacultadCienciasTecnologicas;