import type { Docente } from "@/types/docente";
import type { Departamento } from "@/types/departamento";

const docentesFacultadCiencias: Docente[] = [
  {
    nombreCompleto: "Elky Marcela Bock Argueta",
    nombre: "Elky",
    apellido: "Bock",
    cargo: "Decana",
    grado: "M.Sc. en Gestión de Proyectos de Desarrollo",
    area: "",
    correo: "ebock@unag.edu.hn",
  },
  {
    nombreCompleto: "Glenda Esperanza Rodríguez",
    nombre: "Glenda",
    apellido: "Rodríguez",
    cargo: "Secretaria de Facultad",
    grado: "Licenciatura en Letras y Lenguas",
    area: "Área de desempeño profesional: Letras y Lenguas",
    correo: "grodriguez@unag.edu.hn",
  },
  {
    nombreCompleto: "Douglas Domingo Flores",
    nombre: "Douglas",
    apellido: "Flores",
    cargo: "Jefe de departamento académico de Biología y Microbiología",
    grado: "M.Sc. en Economía y Desarrollo",
    area: "Área de desempeño profesional: Biología",
    correo: "dflores@unag.edu.hn",
  },
  {
    nombreCompleto: "Elky Marcela Bock",
    nombre: "Elky",
    apellido: "Bock",
    cargo: "Jefe de departamento académico de Química",
    grado: "M.Sc. en procesamiento de Alimentos",
    area: "Área de desempeño profesional: Química",
    correo: "ebock@unag.edu.hn",
  },
  {
    nombreCompleto: "Luis Francisco Rivera",
    nombre: "Luis",
    apellido: "Rivera",
    cargo: "Jefe de departamento académico de Matemática, Física e Informática",
    grado: "Licenciatura en Matemáticas",
    area: "Área de desempeño profesional: Matemáticas",
    correo: "lrivera@unag.edu.hn",
  },
  {
    nombreCompleto: "Marla Jiménez",
    nombre: "Marla",
    apellido: "Jiménez",
    cargo: "Jefe de departamento académico",
    grado: "Licenciatura en Administración de Empresas Agrícolas",
    area: "Área de desempeño profesional: Administrativa",
    correo: "mjimenez@unag.edu.hn",
  },
];

export default docentesFacultadCiencias;

export const departamentosCiencias: Departamento[] = [
  {
    id: "biologia",
    nombre: "Biología y Microbiología",
    logo: "/img/facultades/facultad-ciencias/microbiologia-unag.png",
    placeholder: "BM",
    descripcion:
      "Departamento dedicado al estudio de los seres vivos, los microorganismos y sus interacciones con el entorno. Forma profesionales con sólidas bases en ciencias biológicas orientadas a la investigación y la salud.",
    docentes: [
      {
        nombreCompleto: "Melba Carolina Ramirez Ponce",
        nombre: "Melba",
        apellido: "Ramirez",
        cargo: "Docente",
        grado: "Licenciada en Biología / Egresada de la Maestría en Educación en Ciencias Naturales con orientación en la enseñanza de la Biología",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "",
      },
      {
        nombreCompleto: "Henrry Osman Bonilla Matute",
        nombre: "Henrry",
        apellido: "Bonilla",
        cargo: "Docente",
        grado: "Licenciado en Biología",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "",
      },
      {
        nombreCompleto: "Sonia Dorina Escobar Jimenez",
        nombre: "Sonia",
        apellido: "Escobar",
        cargo: "Docente",
        grado: "Licenciada en Biología",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "",
      },
      {
        nombreCompleto: "Rafael Eduardo Ponce Diaz",
        nombre: "Rafael",
        apellido: "Ponce",
        cargo: "Docente",
        grado: "Licenciado en Biología",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "",
      },
      {
        nombreCompleto: "Douglas Domingo Flores Sánchez",
        nombre: "Douglas",
        apellido: "Flores",
        cargo: "Jefe de Departamento / Docente",
        grado: "Licenciado en Biología con énfasis en Zoología / M.Sc. en Economía y Desarrollo",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "dflores@unag.edu.hn",
      },
      {
        nombreCompleto: "Melissa Giselle Ramírez Fiallos",
        nombre: "Melissa",
        apellido: "Ramírez",
        cargo: "Docente",
        grado: "Licenciada en Biología",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "",
      },
      {
        nombreCompleto: "Nora Cecila Martinez Díaz",
        nombre: "Nora",
        apellido: "Martinez",
        cargo: "Docente",
        grado: "Licenciada en Biología con énfasis en Botánica / Maestría en Gerencia de Proyectos de Desarrollo",
        area: "Área de desempeño profesional: Biología y Microbiología",
        correo: "",
      },
    ],
  },
  {
    id: "quimica",
    nombre: "Química",
    logo: "/img/facultades/facultad-ciencias/depto-quimica.png",
    placeholder: "Q",
    descripcion:
      "Departamento enfocado en el estudio de la materia, sus propiedades, composición y transformaciones. Ofrece formación teórica y práctica en química general, analítica y aplicada.",
    docentes: [
      {
        nombreCompleto: "Ivon Aracely Zelaya Muñoz",
        nombre: "Ivon",
        apellido: "Zelaya",
        cargo: "Docente",
        grado: "Dra. / M.Sc. en Gestión de la Calidad Total",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Karla Mariella Hernandez",
        nombre: "Karla",
        apellido: "Hernandez",
        cargo: "Docente",
        grado: "",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Elky Marcela Bock",
        nombre: "Elky",
        apellido: "Bock",
        cargo: "Jefe de Departamento / Docente",
        grado: "Dra. en Ciencias Químicas y Farmacia",
        area: "Área de desempeño profesional: Química",
        correo: "ebock@unag.edu.hn",
      },
      {
        nombreCompleto: "Dilcia Gabriela Macias",
        nombre: "Dilcia",
        apellido: "Macias",
        cargo: "Docente",
        grado: "Dra. en Ciencias Químicas y Farmacia / M.Sc. en Seguridad Alimentaria y Nutricional",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Danelia Jazmín Medina Reyes",
        nombre: "Danelia",
        apellido: "Medina",
        cargo: "Docente",
        grado: "Ing. Químico Industrial / M.Sc. en Dirección Empresarial",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Elia Suyapa Rivera",
        nombre: "Elia",
        apellido: "Rivera",
        cargo: "Docente",
        grado: "Ph.D. en Biotecnología y Bioprocesos Agroindustriales / M.Sc. en Salud y Nutrición / Dra. en Ciencias Químicas y Farmacia",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Cintia Yojana Marcia",
        nombre: "Cintia",
        apellido: "Marcia",
        cargo: "Docente",
        grado: "Ing. Químico Industrial",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Nora Maria Murillo",
        nombre: "Nora",
        apellido: "Murillo",
        cargo: "Docente",
        grado: "Dra. en Ciencias Químicas y Farmacia / M.Sc. en Epidemiología",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Isis Yanira Aceituno",
        nombre: "Isis",
        apellido: "Aceituno",
        cargo: "Docente",
        grado: "Dra. en Ciencias Químicas y Farmacia",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
      {
        nombreCompleto: "Betsabe Zobeyda Venegas",
        nombre: "Betsabe",
        apellido: "Venegas",
        cargo: "Docente",
        grado: "Dra. en Ciencias Químicas y Farmacia / M.Sc. en Salud y Nutrición",
        area: "Área de desempeño profesional: Química",
        correo: "",
      },
    ],
  },
  {
    id: "damfi",
    nombre: "Matemática, Física e Informática",
    logo: "/img/facultades/facultad-ciencias/damfi-unag.png",
    placeholder: "MFI",
    descripcion:
      "Departamento que integra las ciencias exactas con la tecnología de la información. Promueve el pensamiento lógico-matemático y el desarrollo de competencias computacionales en sus estudiantes.",
    docentes: [
      {
        nombreCompleto: "Saulo Semir Aguiriano Andino",
        nombre: "Saulo",
        apellido: "Aguiriano",
        cargo: "Docente",
        grado: "Licenciado en Matemática con Orientación en Ingeniería Matemática / M.Sc. en Matemática Educativa",
        area: "Área de desempeño profesional: Matemáticas",
        correo: "",
      },
      {
        nombreCompleto: "Zonia Pastora Meza Turcios",
        nombre: "Zonia",
        apellido: "Meza",
        cargo: "Docente",
        grado: "Licenciada en Educación Media en Matemáticas con Orientación en Computación",
        area: "Área de desempeño profesional: Matemáticas e Informática",
        correo: "",
      },
      {
        nombreCompleto: "Iris Mariela Duarte Mejía",
        nombre: "Iris",
        apellido: "Duarte",
        cargo: "Docente",
        grado: "Dra. en Matemática Educativa / M.Sc. en Matemática Educativa",
        area: "Área de desempeño profesional: Matemáticas",
        correo: "",
      },
      {
        nombreCompleto: "Víctor Javier Gonzales Santos",
        nombre: "Víctor",
        apellido: "Gonzales",
        cargo: "Docente",
        grado: "Licenciado en Matemáticas / M.Sc. en Formulación y Evaluación de Proyectos",
        area: "Área de desempeño profesional: Matemáticas",
        correo: "",
      },
      {
        nombreCompleto: "Jorge Luis Salgado Lara",
        nombre: "Jorge",
        apellido: "Salgado",
        cargo: "Docente",
        grado: "Licenciado en Física / M.Sc. en Ciencia y Tecnología de Materiales",
        area: "Área de desempeño profesional: Física",
        correo: "",
      },
      {
        nombreCompleto: "Liliam Ramirez Gomez",
        nombre: "Liliam",
        apellido: "Ramirez",
        cargo: "Docente",
        grado: "Licenciada en Informática Educativa",
        area: "Área de desempeño profesional: Informática",
        correo: "",
      },
      {
        nombreCompleto: "Andrés José Murillo Zapata",
        nombre: "Andrés",
        apellido: "Murillo",
        cargo: "Docente",
        grado: "Licenciado en Matemáticas con Orientación en Física / Egresado de la Maestría en Matemática Educativa",
        area: "Área de desempeño profesional: Matemáticas",
        correo: "",
      },
      {
        nombreCompleto: "Luis Francisco Rivera Amador",
        nombre: "Luis",
        apellido: "Rivera",
        cargo: "Jefe de Departamento / Docente",
        grado: "Licenciado en Matemática con Orientación en Ingeniería Matemática / Egresado de la Maestría en Matemática Educativa",
        area: "Área de desempeño profesional: Matemáticas",
        correo: "lrivera@unag.edu.hn",
      },
      {
        nombreCompleto: "Ester Abigail Zapata Quintanilla",
        nombre: "Ester",
        apellido: "Zapata",
        cargo: "Docente",
        grado: "Licenciada en Matemática con Orientación en Estadística",
        area: "Área de desempeño profesional: Matemáticas",
        correo: "",
      },
      {
        nombreCompleto: "Joel Luis Santos Melara",
        nombre: "Joel",
        apellido: "Santos",
        cargo: "Docente",
        grado: "Ingeniero en Sistemas",
        area: "Área de desempeño profesional: Informática",
        correo: "",
      },
      {
        nombreCompleto: "Wilder Hermogenes Guerrero",
        nombre: "Wilder",
        apellido: "Guerrero",
        cargo: "Docente",
        grado: "Licenciado en Física",
        area: "Área de desempeño profesional: Física",
        correo: "",
      },
    ],
  },
  {
    id: "letras",
    nombre: "Letras y Lenguas",
    logo: "/img/facultades/facultad-ciencias/depto-letras.png",
    placeholder: "LL",
    descripcion:
      "Departamento comprometido con el estudio del lenguaje, la literatura y las ciencias de la comunicación. Cultiva la expresión oral y escrita, la investigación lingüística y la apreciación literaria.",
    docentes: [
      {
        nombreCompleto: "María José Talavera Palacios",
        nombre: "María",
        apellido: "Talavera",
        cargo: "Docente",
        grado: "Licenciada en la Enseñanza de Inglés / M.A. en TESOL",
        area: "Área de desempeño profesional: Inglés",
        correo: "",
      },
      {
        nombreCompleto: "Claudia Karina Hernández Sánchez",
        nombre: "Claudia",
        apellido: "Hernández",
        cargo: "Docente",
        grado: "Licenciada en Letras con orientación en Lingüística",
        area: "Área de desempeño profesional: Letras y Lenguas",
        correo: "",
      },
      {
        nombreCompleto: "Jared Said Mejia Velasquez",
        nombre: "Jared",
        apellido: "Mejia",
        cargo: "Docente",
        grado: "Licenciado en la Enseñanza del Inglés",
        area: "Área de desempeño profesional: Inglés",
        correo: "",
      },
      {
        nombreCompleto: "Glenda Esperanza Rodríguez Galo",
        nombre: "Glenda",
        apellido: "Rodríguez",
        cargo: "Secretaria de Facultad / Docente",
        grado: "Licenciada en Letras con orientación en Lingüística",
        area: "Área de desempeño profesional: Letras y Lenguas",
        correo: "grodriguez@unag.edu.hn",
      },
      {
        nombreCompleto: "Rebeca Maria Figueroa Mejia",
        nombre: "Rebeca",
        apellido: "Figueroa",
        cargo: "Docente",
        grado: "Licenciada en la Enseñanza del Inglés",
        area: "Área de desempeño profesional: Inglés",
        correo: "",
      },
      {
        nombreCompleto: "Eleana Gissel García Laínez",
        nombre: "Eleana",
        apellido: "García",
        cargo: "Docente",
        grado: "Licenciada en la Enseñanza del Inglés",
        area: "Área de desempeño profesional: Inglés",
        correo: "",
      },
    ],
  },
  {
    id: "sociales",
    nombre: "Sociales y Humanidades",
    logo: null,
    placeholder: "SH",
    descripcion:
      "Departamento orientado al análisis crítico de la sociedad, la historia y la cultura. Forma profesionales con visión humanista capaces de comprender y transformar su entorno social.",
    docentes: [
      {
        nombreCompleto: "Orlando David Murillo Lizardo",
        nombre: "Orlando",
        apellido: "Murillo",
        cargo: "Docente",
        grado: "Licenciado en Historia / M.Sc. en Curriculum / Ph.D. en Educación",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Elisa Isabel Rivera Amador",
        nombre: "Elisa",
        apellido: "Rivera",
        cargo: "Docente",
        grado: "M.Sc. en Economía y Desarrollo",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Gerardo Rafael Moya Izaguirre",
        nombre: "Gerardo",
        apellido: "Moya",
        cargo: "Docente",
        grado: "M.Sc. en Economía y Desarrollo",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Carlos Alberto Alvarado Hernandez",
        nombre: "Carlos",
        apellido: "Alvarado",
        cargo: "Docente",
        grado: "M.Sc. en Investigación Educativa",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Carlos Gehovanny Ordoñez Vayona",
        nombre: "Carlos",
        apellido: "Ordoñez",
        cargo: "Docente",
        grado: "Licenciado en Sociología",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Saira Carolina Zalaya García",
        nombre: "Saira",
        apellido: "Zalaya",
        cargo: "Docente",
        grado: "Licenciada en Ciencias Sociales",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Kenny Melissa Castillo",
        nombre: "Kenny",
        apellido: "Castillo",
        cargo: "Docente",
        grado: "M.Sc. en Dirección de Recursos Humanos",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Miguel Rafael Velasquez",
        nombre: "Miguel",
        apellido: "Velasquez",
        cargo: "Docente",
        grado: "M.Sc. en Psicología Educativa",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
      {
        nombreCompleto: "Daniel Josue Rivera Amador",
        nombre: "Daniel",
        apellido: "Rivera",
        cargo: "Docente",
        grado: "Licenciado en Ciencias Sociales",
        area: "Área de desempeño profesional: Ciencias Sociales",
        correo: "",
      },
    ],
  },
];
