import type { Docente } from "@/types/docente";

const docentesFacultadCienciasEconomicas: Docente[] = [
  {
    nombreCompleto: "Neris Yessenia Escobar Ramos",
    nombre: "Neris",
    apellido: "Escobar",
    cargo: "Decana de la Facultad",
    grado: "Licenciatura en Administración de Empresas, Maestría en Gestión de Proyectos",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Alex René Dubón",
    nombre: "Alex",
    apellido: "Dubón",
    cargo: "Jefe del Departamento de Economía Sectorial, Docente",
    grado: "Licenciatura en Economía Agrícola, Maestría en Ciencias",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Norman Leonel Mercadal Tejada",
    nombre: "Norman",
    apellido: "Mercadal",
    cargo: "Jefe del Departamento de Organización y Dirección Empresarial, Docente",
    grado: "Ingeniero Agrónomo",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Selmira Azucena Cruz Ávila",
    nombre: "Selmira",
    apellido: "Cruz",
    cargo: "Coordinadora de la carrera de Administración de Empresas Agropecuarias, Docente",
    grado: "Licenciatura en Comercio Internacional con Orientación en la Agroindustria, Máster en Economía y Finanzas",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Karen Evelia Lara Cruz",
    nombre: "Karen",
    apellido: "Lara",
    cargo: "Coordinadora de la carrera de Economía Social Agraria, Docente",
    grado: "Licenciatura en Mercadotecnia, Máster en Economía y Finanzas",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Francisco Javier Medina",
    nombre: "Francisco",
    apellido: "Medina",
    cargo: "Secretario General, Docente",
    grado: "Licenciado en Economía Agrícola, Master en Economía Ambiental y Administración de los Recursos Naturales, Master en Educación Superior",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Mariela Alemán Casco",
    nombre: "Mariela",
    apellido: "Alemán",
    cargo: "Docente",
    grado: "Máster en Gestión de Proyectos",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Leslie Waleska Escobar Sánchez",
    nombre: "Leslie",
    apellido: "Escobar",
    cargo: "Docente",
    grado: "Licenciatura en Administración, Máster en Gestión de la Calidad Total, Master en Economía y Finanzas",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Miriam Anabel Alvarado",
    nombre: "Miriam",
    apellido: "Alvarado",
    cargo: "Docente",
    grado: "Licenciatura en Economía Agrícola, Máster en Gestión de la Calidad Total",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Mariano Enrique Guillén Moreno",
    nombre: "Mariano",
    apellido: "Guillén",
    cargo: "Secretario de la Facultad de Ciencias Económicas y Administrativas, Docente",
    grado: "Ingeniero Agrónomo",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "José Antonio Padilla",
    nombre: "José",
    apellido: "Padilla",
    cargo: "Docente",
    grado: "Licenciatura en Administración de Empresas, Maestría en Economía y Desarrollo",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "José Luis Castillo Lanza",
    nombre: "José",
    apellido: "Castillo",
    cargo: "Docente",
    grado: "Ingeniero Agrónomo, Master en Gerencia de Proyectos de Desarrollo Agrícola",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Tony Dester Escobar Sánchez",
    nombre: "Tony",
    apellido: "Escobar",
    cargo: "Docente",
    grado: "Licenciado en Administración de Empresas, Licenciado en Informática Educativa",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Linda María Molina Solís",
    nombre: "Linda",
    apellido: "Molina",
    cargo: "Docente",
    grado: "Licenciatura en Psicología, Máster en Dirección de Recursos Humanos",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Elkin Armando Herrera",
    nombre: "Elkin",
    apellido: "Herrera",
    cargo: "Asistente de la Dirección de Admisiones",
    grado: "Licenciado en Administración de Empresas Agropecuarias, Master en Economía y Finanzas, Doctor en Ciencias con orientación en Ciencias Administrativas, Posdoctorante en Desarrollo Económico, Innovación y Gestión Empresarial",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Sergio Samuel Moya Izaguirre",
    nombre: "Sergio",
    apellido: "Moya",
    cargo: "Docente",
    grado: "Licenciado en Administración de Empresas, Master en Economía y Finanzas",
    area: "Economía Sectorial",
    correo: "",
  },
  {
    nombreCompleto: "Mauricio Alberto Moreno Escobar",
    nombre: "Mauricio",
    apellido: "Moreno",
    cargo: "Docente",
    grado: "Ingeniero Agrónomo, Master en Formulación de Proyectos",
    area: "Organización y Dirección Empresarial",
    correo: "",
  },
  {
    nombreCompleto: "Bessy Esmeralda Mejía Cálix",
    nombre: "Bessy",
    apellido: "Mejía",
    cargo: "Docente",
    grado: "Ingeniera Industrial, Maestría en Gestión de Proyectos",
    area: "",
    correo: "",
  },
];

export default docentesFacultadCienciasEconomicas;
