name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          script: |
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S -u root bash -c '
            cd /home/unagedu/public_html/unag.edu.hn &&
            git pull origin main &&
            source /root/.bash_profile &&
            nvm use 22 &&
            bun install &&
            bun run build &&
            pm2 restart portal-unag
            '